spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: hyeongkyu
    password: hk987852!
    driver-class-name: org.postgresql.Driver

jwt:
  secret-key: "O1Z1PoOE4gHosQ3/kfyaeC6eXy5rnU1CDovbKDKYUYQ="
  access-token-expire-period : 3600
  refresh-token-expire-period : 604800


